title: Data Day
description: > # this means to ignore newlines until "baseurl:"
  Data related content with a skewed distribution of upload frequency.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Daphne LeSueur # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am a data scientist focused on data. # add description
social-twitter: # add your Twitter handle
social-facebook: Daphne LeSueur Wilkinson # add your Facebook handle
social-github: dlesueur # add your Github handle
social-linkedin: Daphne LeSueur # add your Linkedin handle
social-email: daphnelesueur@gmail.com # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
