title: Data Day 
description: > # this means to ignore newlines until "baseurl:"
  Data-driven content with a skewed post frequency distribution. 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Daphne LeSueur # add your name
author-img: assets/img/daphne.jpeg # add your photo
about-author: I'm a data scientist focusing on data!
social-twitter: # add your Twitter handle
social-facebook: Daphne LeSueur Wilkinson
social-github: dlesueur # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: daphnelesueur@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
